### ISSUE TITLE
Updates should not be done via `composer require`

### ISSUE THREAD

**Issue by greg-1-anderson** [dependencies-io/actor-php-composer#16]
If a `composer lock` file exists, then `composer require` should not be used to update dependencies. In general, for projects that commit a `composer.lock` file, it is better to use `composer update` to generate the exact dependency updates to use. This leaves the composer.json file and its version constraints unmodified, and records the updated version to use in the composer.lock file, as intended by Composer.

The existing algorithm fails in common scenarios. As illustrated in #7 and #8, if there is a project that requires some Symfony components at `^3.4`, and there is `^4` available, using `composer require` one component at a time to go from `^3` to `^4` is likely to result in a failure, as the 3.x and 4.x components will not always work together.

A better strategy would be to use `composer update` whenever possible (whenever a `composer.lock` file is available), and reserve `composer require` for those projects that do not commit a lock file.

**Comment by greg-1-anderson** [comment]
It is also inconvenient that dependencies are updated one PR at a time. It would be better if a single PR with all updated dependencies included was made. Perhaps the idea is that multiple PRs allow the maintainer to determine which update caused a problem when there are failures; however, it is often not possible to update just a single version constraint in composer.json. This is not an issue if only composer.lock is updated as previously suggested.

Additionally, here is an example of a failure that can happen by using `composer require` instead of `composer update`:

https://travis-ci.org/consolidation/Robo/builds/349093523?utm_source=github_status&utm_medium=notification

Here, the version constraints in composer.json are keeping the versions of the dependencies selected to versions that work correctly with the version of PHP used in each of the tests above. The test variant that are passing are the "highest" and "lowest" tests, which force a composer update.

For more details on highest/lowest testing https://pantheon.io/blog/highest-lowest-testing-multiple-symfony-versions

**Comment by davegaeddert** [comment]
Hey @greg-1-anderson, thanks for the feedback. We've come to the same conclusions, and have been working on a completely overhauled update system that separates things into "lockfiles" and "manifests" so that we can provide the two different flows you suggested. If you're curious, the new repo for PHP is here: https://github.com/dependencies-io/php

We're hoping to get everything finished up and roll it out real soon!

Let me know if you have any other questions in the meantime.

**Comment by greg-1-anderson** [comment]
Thanks for the quick reply, @davegaeddert. I skimmed through the new repo, and it does in fact look to be about right. It's nice that there's just one pull request created at the end of the actor (presuming that the actor is called at most once per composer.json location.) However, it looks like the actor is still running `composer require` to modify the composer.json file. I think it would be best to skip this step, and rely on what the `composer update` drops in the lock file. You could simply `throw` if there is no lock file, and not worry about the non-lockfile case. Updating dependencies doesn't make a lot of sense when there isn't a lock file; bumping the version in composer.json is usually only the right thing to do if the project specifically depends on some bugfix or new feature in that version. Nowadays, a lot of people (myself included) encourage folks to always include a composer.lock file in their projects -- even for php libraries. This works well if doing highest/lowest testing.

Is there any way for me to run the new php collector/actor as a pre-release, for testing? If that were possible, I could submit a PR to the project to illustrate what I'm suggesting.

**Comment by greg-1-anderson** [comment]
Hm, the bot retried my broken build today, even though I made no changes. (https://github.com/consolidation/Robo/issues/686)

**Comment by davegaeddert** [comment]
The builds run every day (you can change to weekly or monthly in settings if you want) because dependencies get updated regardless of whether *you* made any changes -- that's how we help you keep things updated over time.

On the other comments, I think we actually cover everything you're talking about in the new version, it's just not totally clear yet without some explanation/documentation. [`composer update` is used for any changes in-range of your composer.json requirements](https://github.com/dependencies-io/php/blob/master/src/act.php#L12), meaning that we'll help you keep your composer.lock up-to-date at all times. `composer require` still has a role though in letting you know when new versions *outsite* of your package.json range are released -- so that you can use "safe" ranges but still be notified when new major versions (or anything above your range) is released.

I think it will make more sense when you see it, and if not then I definitely will want to know! Several people have been asking to get an early preview so we're trying to get that put together as quickly as possible. We just need to finalize a few things in the UI and new dependencies.yml format and then I'll get in touch with you.

Thanks!

**Comment by greg-1-anderson** [comment]
> The builds run every day (you can change to weekly or monthly in settings if you want) because dependencies get updated regardless of whether you made any changes

As an optimization, you could skip this for failed builds. Not super important, though.

In any event I look forward to trying out the new version.

**Comment by davegaeddert** [comment]
Hey @greg-1-anderson, I forked your repo to try out the new update system. Based on the contents right now, it created 2 PRs (instead of the 10+ that you got) which you can see here: https://github.com/davegaeddert/Robo/pulls

Just at a glance, does that seem to make more sense than the experience you had the first time around?

I'd be happy to give you a link to the new interface and help get you up and running if you're interested. Thanks!

**Comment by greg-1-anderson** [comment]
Thanks @davegaeddert, that's a big improvement!  It does make sense that there are two PRs here. The one for composer.lock has all of the updates that could be applied to composer.lock. The other is for cssmin, which I have pegged in composer.json at 3.0.4, because 3.0.5 didn't work for the project. Dependencies.io brought me up to 3.0.6; it would be interesting to see if the tests pass with that version. I'm also curious, if the tests **don't** pass, is dependencies.io going to keep making new PRs that I have to close, or will it see that there's an open PR for 3.0.6, and leave that as-is until a 3.0.7 comes out.

The other thing I notice is that if I update my project locally via `composer update`, I get:
```
Loading composer repositories with package information
Updating dependencies (including require-dev)
Package operations: 0 installs, 12 updates, 0 removals
  - Updating symfony/finder (v3.4.5 => v3.4.6): Loading from cache
  - Updating symfony/debug (v3.4.5 => v3.4.6): Loading from cache
  - Updating symfony/console (v3.4.5 => v3.4.6):  Checking out 067339e9b8
  - Updating symfony/process (v3.4.5 => v3.4.6): Loading from cache
  - Updating symfony/event-dispatcher (v3.4.5 => v3.4.6): Loading from cache
  - Updating symfony/yaml (v3.4.5 => v3.4.6): Loading from cache
  - Updating symfony/filesystem (v3.4.5 => v3.4.6): Loading from cache
  - Updating symfony/config (v3.4.5 => v3.4.6): Loading from cache
  - Updating symfony/stopwatch (v3.4.5 => v3.4.6): Loading from cache
  - Updating symfony/dom-crawler (v3.4.5 => v3.4.6): Loading from cache
  - Updating symfony/browser-kit (v3.4.5 => v3.4.6): Loading from cache
  - Updating symfony/css-selector (v3.4.5 => v3.4.6): Loading from cache
```
However, dependencies.io wants to bring me all the way up to Symfony 4.0, which isn't desirable, because my composer.json keeps me on Symfony 3 for the main project. I am held to Symfony 3 because I have the following in my composer.json:
```
    "config": {
        "platform": {
            "php": "5.6.3"
        }
    },
```
Symfony 4 is not compatible with php 5.6, so my platform dependency (that statement makes Composer evaluate all of its dependencies as if the running version of php was 5.6) keeps me on Symfony 3. Now, if some other project includes Robo as a dependency, the platform configuration is ignored, and Symfony 4 is allowed.

Now, this arrangement probably isn't strictly necessary. I could reorganize it so that my composer.json was configured for the highest dependencies (e.g. Symfony 4), and I could explicitly install Symfony 3 components before building my phar (compiled php application). That would meet my needs, and probably work with dependencies.io. I'll probably do that transformation. However, this situation does bring up the point that there are a lot of complex reasons why composer might apply certain version constraints. From the observed PR, it seems that dependencies.io is using its own metadata to decide what version to upgrade to. It might be better to use `composer update` to generate the lockfile updates, so that the updated versions come out the same. That would avoid creating PRs that use newer versions than are allowed in the project -- which is fine for a standalone "hey let's try this" PR like the cssmin example above, but not as good for the standard "hey here are your new dependency updates" PR.

I'd be very interested in trying the new interface out.

**Comment by greg-1-anderson** [comment]
I should also mention that my project actually contains three composer.json files: the main one for Symfony 3, one for Symfony 4, and one for Symfony 2. The last is only used in "lowest" testing, so it does not have a composer.lock file, but the other two do. If you run `composer update`, then it will update both of the lock files.

**Comment by davegaeddert** [comment]
Thanks for the response @greg-1-anderson. I think that all makes sense and those are good questions. I'll try to answer them!

> I'm also curious, if the tests don't pass, is dependencies.io going to keep making new PRs that I have to close, or will it see that there's an open PR for 3.0.6, and leave that as-is until a 3.0.7 comes out.

Dependencies.io currently doesn't look at your test results, but it will only send you an update for a specific version **once**. So if you get a PR for 3.0.6 and decide to just close it, then nothing else will happen until 3.0.7 comes out. If you leave the 3.0.6 PR open but don't do anything with it, it will be closed automatically when the new PR for 3.0.7 arrives. If you decide that anything > 3.0.5 isn't ever going to work, then the next step would probably be to just ignore that dependency or those specific ranges via settings in dependencies.yml. We've got a pretty flexible syntax that would let you say, "don't send me any updates for 3.x.x on cssmin, but let me know when 4.x.x comes out".

> However, dependencies.io wants to bring me all the way up to Symfony 4.0

> If you run composer update, then it will update both of the lock files.

I had some looong answers written up to discuss these, but instead I'll just point you to a new PR: https://github.com/davegaeddert/Robo/pull/3

The gist is that by default we're using `--ignore-platform-reqs` and `--ignore-scripts` with composer (but otherwise try to always use the native tools/commands where possible). I think there were reasons for both, but to be honest I'll have to track down those conversations to remember the specifics. For now though, I've left them as the defaults and added an optional user-setting so that you can change the composer options. Seems to work fine for your case? The other potential thing we can do here is allow users to choose which PHP version (container image) to use -- but we've tried to avoid that so far just because of added complexity.

---

Ok so as far as trying the new interface, just log in to the app and then there is a semi-hidden link to the v2 preview in the sidebar. You have to hover over it, but it's right above the settings icon:
![clipboard-9e7bc1a0](https://user-images.githubusercontent.com/649496/37313359-d9d2e640-261c-11e8-99dc-4af1c14a0bf3.png)

Some of this is still being worked on, but it should be far enough along for you to try. Let me know if you run into any issues with it.

You'll need to update your dependencies.yml to the new format to customize things and enable the automated updates on the new version. I went ahead and just sent you a PR for that here: https://github.com/consolidation/Robo/pull/699

Thanks for taking the time! Let me know what you think.

**Comment by greg-1-anderson** [comment]
Thanks for https://github.com/consolidation/Robo/pull/699; I'll merge it and turn on v2 and see what happens.
```
The gist is that by default we're using --ignore-platform-reqs and --ignore-scripts with composer (but otherwise try to always use the native tools/commands where possible). I think there were reasons for both
```
I'm not sure I understand why you'd use `--ignore-platform-reqs`. I guess if you didn't use `--ignore-scripts`, then folks could run their scripts on your update infrastructure, and the results of that may or may not be predictable. In any event, https://github.com/davegaeddert/Robo/pull/3 came out perfectly. If you turned off `--ignore-platform-reqs` and `--ignore-script`, thanks! If you made it work some other way, I guess I don't need to worry about it too much. I'll look and see if the optional user-setting  you mentioned is in your admin UI.

Looks like it's all coming together, anyway -- I'll try it out and let you know how it goes.

**Comment by greg-1-anderson** [comment]
Does setting [composer options](https://github.com/consolidation/Robo/pull/699/files#diff-b46350d242d2a2e3d1436e201b851f8dR6) override the defaults ( --ignore-platform-reqs and --ignore-scripts)?

**Comment by davegaeddert** [comment]
Yes it does: https://github.com/dependencies-io/php/blob/master/src/composer.php#L3-L7

**Comment by greg-1-anderson** [comment]
The v2 PRs are looking really good. They still have this warning:

> We didn't find any content for v3.4.6. Feel free to open an issue at https://github.com/dependencies-io/support to suggest any improvements.

I don't know what that means; it seems that the update of the Symfony components went fine, regardless of the warning message.

Two more questions:

1. Do you expect that the v2 API will ship by 9 April? If not, may I publicly discuss the v2 API at a conference? At DrupalCon Vienna last year I gave a talk, [Automate your Automation](https://events.drupal.org/vienna2017/sessions/automate-your-automation). In this presentation I included a bespoke script that used the [composer lock updater](https://github.com/danielbachhuber/composer-lock-updater) project to update dependencies. I'm giving this talk again at [DrupalCon Nashville](https://events.drupal.org/nashville2018/sessions/automate-your-automation), and would like to replace this content with dependencies-io.

2. Also updated for the new presentation is my new [php starter project](https://github.com/g-1-a/starter). The README lists all of the things it does, but the tl;dnr version is that you just need to run `composer create-project` on it (providing a GITHUB_TOKEN for authentication), and it will also set up a GitHub repository and start Travis tests running. I already have a dependencies.yml (which I will now need to update for v2) included, so all folks would need to do is visit dependencies.io and turn on their new project to get updates. If there was a web API or cli tool to turn on dependencies.io projects, I'd love to turn on dependency updates at the same time I enable Travis testing. Just a nice-to-have, but people get pretty excited about do-it-for-me automation tools.

**Comment by greg-1-anderson** [comment]
Regarding (2), I see that this currently just links in to GitHub's admin interface to configure dependencies.io on any given GitHub project. I therefore should be able to automate this through the GitHub API. I'll look into that.

**Comment by greg-1-anderson** [comment]
<img width="609" alt="screen shot 2018-03-12 at 5 36 15 pm" src="https://user-images.githubusercontent.com/612191/37316436-4ac4650a-261c-11e8-87ad-8dd945d420cb.png">

If "all repositories" is selected, will dependencies.io quietly and efficiently ignore any repo that does not have a dependencies.yaml file? If so, then the "turn it on" step only has to happen once per org.

**Comment by davegaeddert** [comment]
Great! Those warnings are for not being able to find the CHANGELOG (or other release notes). We're going to refocus on that here soon hopefully but wanted to make sure we nail down the rest of the v2 system first.

1. Yep, we're planning to ship it by the end of March at the latest. We're getting the first set of people started this week while we work out the remaining kinks, and then we'll start publicizing it once everything feels good. It'd be great to see dependencies.io included in your talk. I've talked with a few Drupal people in the past (and Daniel, actually) but feel like now we will finally have the right pieces to provide good updates for those users. I'll have to watch your talk from last year! We can be in conversation about this -- but let me know if you want a logo file or something to use. You can email me at dave.gaeddert at dropseed.io.

2. Sounds like you've got a couple things you can look into here. Again, it'd be great if you're interested in including dependencies.io. Let me know if I can be helpful on this. I'm not actually sure if GitHub has opened that part up via the API or not...

On the repository access, yes it should be fine to turn it on for the org. It will run once when the repo is added (and we'll be notified for push events, etc.) but it won't ever perform any updates unless you put a dependencies.yml in place or use the buttons in the interface. That being said, if someone is really just going to use it on 1 or 2 repos, I'd advise enabling it on those individually -- otherwise we are given access to potentially private code that we just don't need, and those webhooks are sent to us without any real benefit.

**Comment by davegaeddert** [comment]
Also forgot to mention that the --ignore-platform-reqs and --ignore-scripts are no longer used by default on the PHP component. So you can remove that setting I added if you want to. Thanks!

**Comment by greg-1-anderson** [comment]
I was partially successful with auto-configuring dependencies.io on a project.

I used the API I mentioned above: https://developer.github.com/v3/apps/installations/#add-repository-to-installation

PUT /user/installations/:installation_id/repositories/:repository_id

This worked when I hardcoded the :installation_id and :repository_id for a repo in a project that already had at least one repo with dependencies.io configured.  Only an ordinary authentication with a GITHUB_TOKEN was required.

I can find the id of a repo via https://developer.github.com/v3/repos/#get

However, the :installation_id is a bit of a sticking point. This id varies depending on the organization, and does not exist at all until dependencies.io has been installed on that organization. So far I have not found a way to discover the id of a dependencies.io installation on a GitHub organization, and there does not appear to be a way to install a GitHub app on an organization through the API yet.

As a side note, APIs such as [apps/installations#list-repositories](https://developer.github.com/v3/apps/installations/#list-repositories) won't work with a simple GITHUB_TOKEN authentication; a JWT token is required, and [that requires the GitHub app's private key](https://github.com/KnpLabs/php-github-api/blob/master/doc/security.md#authenticating-as-an-integration), which is help by the app's owner.

**Comment by davegaeddert** [comment]
Good to know. It's possible that we could enable some of this through *our* API, but we don't have plans to do that at the moment.

**Comment by davegaeddert** [comment]
Going to close this, any further php discussion can happen on the new repo here: https://github.com/dependencies-io/php

**Comment by greg-1-anderson** [comment]
Yes, this is working well for me now. Thanks for the adjustments!
